### ISSUE TITLE
Descrição da ocorrência de pagamento quando o mesmo é autorizado está incoerente com a especificação

### ISSUE THREAD

**Issue by harrisonlopeslb** [dalvanribeiro/Sistemadegestaodepagamentos#2]
Segundo a especificação, a mensagem inserida na descrição da ocorrência de pagamento no caso de aprovação do mesmo deveria ser: "O NOME DO CARGO não pôde realizar o pagamento no valor X por ser superior ao seu limite Y."

**Comment by fmrenan** [comment]
Corrigido
