### ISSUE TITLE
Falta de informações na descrição da ocorrência em que o autorizador está indisponível

### ISSUE THREAD

**Issue by Spetox** [dalvanribeiro/Sistemadegestaodepagamentos#4]
A mensagem esperada dos casos de teste onde o autorizador está indisponível deveria conter mais detalhes, exemplo: "O Diretor Geral não pôde realizar o pagamento no valor 5000.00 por estar indisponível.", mas está retornando somente "Diretor Geral indisponível".
Isso para todos os autorizadores de pagamento.

**Comment by fmrenan** [comment]
Corrigido
